version: '3.1'
services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=stalksa
      - POSTGRES_PASSWORD=11111
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - '5432:5432'
